// Auto-generated by scripts/generate-mystery-verses.ts — do not edit manually
import type { MysteryDescription } from './mysteryDescriptions';

export const mysteryVerseData: Record<string, MysteryDescription[]> = {
	"lichtreichen": [
		{
			"title": "Das erste lichtreiche Geheimnis: Die Taufe im Jordan.",
			"reference": "Mt 3, 16-17",
			"text": "«Als aber Jesus getauft war, stieg er sogleich aus dem Wasser heraus; und siehe, es öffneten sich ihm die Himmel, und er sah den Geist Gottes herabkommen über ihn und wie eine Taube herabsteigen. Und siehe, eine Stimme vom Himmel sprach: Dieser ist mein Sohn, der geliebte, an welchem ich Wohlgefallen habe!»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 3,
				"verses": [
					{
						"verse": 16,
						"text": "Als aber Jesus getauft war, stieg er sogleich aus dem Wasser heraus; und siehe, es öffneten sich ihm die Himmel, und er sah den Geist Gottes herabkommen über ihn und wie eine Taube herabsteigen."
					},
					{
						"verse": 17,
						"text": "Und siehe, eine Stimme vom Himmel sprach: Dieser ist mein Sohn, der geliebte, an welchem ich Wohlgefallen habe!"
					}
				]
			}
		},
		{
			"title": "Das zweite lichtreiche Geheimnis: Die Hochzeit von Kana.",
			"reference": "Joh 2, 1-5",
			"text": "«Am dritten Tage ward eine Hochzeit gehalten zu Kana in Galiläa; und die Mutter Jesu war dabei. Auch Jesus und seine Jünger waren zur Hochzeit geladen. Und da der Wein ausging, sagte die Mutter Jesu zu ihm: Sie haben keinen Wein! Jesus aber sprach zu ihr: Weib! was soll dies mir und dir? Noch ist meine Stunde nicht gekommen. Da sagte seine Mutter zu den Dienern: Was immer er euch sagt, das tut!»",
			"verseData": {
				"book": "Johannes",
				"chapter": 2,
				"verses": [
					{
						"verse": 1,
						"text": "Am dritten Tage ward eine Hochzeit gehalten zu Kana in Galiläa; und die Mutter Jesu war dabei."
					},
					{
						"verse": 2,
						"text": "Auch Jesus und seine Jünger waren zur Hochzeit geladen."
					},
					{
						"verse": 3,
						"text": "Und da der Wein ausging, sagte die Mutter Jesu zu ihm: Sie haben keinen Wein!"
					},
					{
						"verse": 4,
						"text": "Jesus aber sprach zu ihr: Weib! was soll dies mir und dir? Noch ist meine Stunde nicht gekommen."
					},
					{
						"verse": 5,
						"text": "Da sagte seine Mutter zu den Dienern: Was immer er euch sagt, das tut!"
					}
				]
			}
		},
		{
			"title": "Das dritte lichtreiche Geheimnis: Die Verkündigung des Reiches Gottes.",
			"reference": "Mk 1, 15",
			"text": "«und sprach: Erfüllet ist die Zeit, und das Reich Gottes hat sich genahet; tuet Buße und dem Evangelium!»",
			"verseData": {
				"book": "Markus",
				"chapter": 1,
				"verses": [
					{
						"verse": 15,
						"text": "und sprach: Erfüllet ist die Zeit, und das Reich Gottes hat sich genahet; tuet Buße und dem Evangelium!"
					}
				]
			}
		},
		{
			"title": "Das vierte lichtreiche Geheimnis: Die Verklärung.",
			"reference": "Mt 17, 1-2",
			"text": "«Nach sechs Tagen nahm Jesus den Petrus, Jakobus und Johannes, Bruder desselben, zu sich, und führte sie allein auf einen hohen Berg. Und er ward vor ihnen verklärt; und sein Angesicht leuchtete wie die Sonne, seine Kleider aber wurden weiß wie der Schnee.»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 17,
				"verses": [
					{
						"verse": 1,
						"text": "Nach sechs Tagen nahm Jesus den Petrus, Jakobus und Johannes, Bruder desselben, zu sich, und führte sie allein auf einen hohen Berg."
					},
					{
						"verse": 2,
						"text": "Und er ward vor ihnen verklärt; und sein Angesicht leuchtete wie die Sonne, seine Kleider aber wurden weiß wie der Schnee."
					}
				]
			}
		},
		{
			"title": "Das fünfte lichtreiche Geheimnis: Die heiligste Eucharistie (Das Altarssakrament).",
			"reference": "Mt 26, 26",
			"text": "«Während sie aber aßen, nahm Jesus Brot, segnete und brach es, gab es seinen Jüngern, und sprach: Nehmet hin, und esset, dies ist mein Leib!»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 26,
				"verses": [
					{
						"verse": 26,
						"text": "Während sie aber aßen, nahm Jesus Brot, segnete und brach es, gab es seinen Jüngern, und sprach: Nehmet hin, und esset, dies ist mein Leib!"
					}
				]
			}
		}
	],
	"freudenreich": [
		{
			"title": "Das erste freudenreiche Geheimnis: Die Verkündigung des Erzengles Gabriel an die Jungfrau Maria.",
			"reference": "Lk 1, 26-27",
			"text": "«Im sechsten Monate aber ward der Engel Gabriel von Gott gesandt in eine Stadt in Galiläa, mit Namen Nazareth, zu einer Jungfrau, die verlobt war mit einem Manne, mit Namen Joseph, vom Hause Davids, und der Name der Jungfrau war Maria.»",
			"verseData": {
				"book": "Lukas",
				"chapter": 1,
				"verses": [
					{
						"verse": 26,
						"text": "Im sechsten Monate aber ward der Engel Gabriel von Gott gesandt in eine Stadt in Galiläa, mit Namen Nazareth,"
					},
					{
						"verse": 27,
						"text": "zu einer Jungfrau, die verlobt war mit einem Manne, mit Namen Joseph, vom Hause Davids, und der Name der Jungfrau war Maria."
					}
				]
			}
		},
		{
			"title": "Das zweite freudenreiche Geheimnis: Der Besuch Marias bei Elisabeth.",
			"reference": "Lk 1, 39-42",
			"text": "«Maria aber machte sich in jenen Tagen auf, und ging eilends auf das Gebirge nach einer Stadt des Stammes Juda. Und sie kam in das Haus des Zacharias, und grüßte Elisabeth. Und es bagab sich, sobald Elisabeth den Gruß Marias hörte, hüpfte das Kind freudig in ihrem Leibe auf, und Elisabeth ward erfüllet von dem heiligen Geiste. Und sie rief mit lauter Stimme, und sprach: Gebenedeit bist du unter den Weibern, und gebenedeiet ist die Frucht deines Leibes!»",
			"verseData": {
				"book": "Lukas",
				"chapter": 1,
				"verses": [
					{
						"verse": 39,
						"text": "Maria aber machte sich in jenen Tagen auf, und ging eilends auf das Gebirge nach einer Stadt des Stammes Juda."
					},
					{
						"verse": 40,
						"text": "Und sie kam in das Haus des Zacharias, und grüßte Elisabeth."
					},
					{
						"verse": 41,
						"text": "Und es bagab sich, sobald Elisabeth den Gruß Marias hörte, hüpfte das Kind freudig in ihrem Leibe auf, und Elisabeth ward erfüllet von dem heiligen Geiste."
					},
					{
						"verse": 42,
						"text": "Und sie rief mit lauter Stimme, und sprach: Gebenedeit bist du unter den Weibern, und gebenedeiet ist die Frucht deines Leibes!"
					}
				]
			}
		},
		{
			"title": "Das dritte freudenreiche Geheimnis: Die Geburt Jesu im Stall von Bethlehem.",
			"reference": "Lk 2, 1-7",
			"text": "«Es geschah aber in denselben Tagen, dass vom Kaiser Augustus ein Befehl ausging, dass der ganze Erdkreis aufgeschrieben werde. Diese Aufschreibung war die erste, und geschah durch Cyrinus, den Statthalter von Syrien. Und alle gingen hin, sich aufschreiben zu lassen, ein jeder in seine Stadt. Da zog auch Joseph von Galiläa, aus der Stadt Nazareth, hinauf nach Judäa in die Stadt Davids, welche Bethlehem heißt, weil er aus dem Hause und Geschlechte Davids war, um sich aufschreiben zu lassen mit Maria, seinem verlobten Weibe, welche schwanger war, Es begab sich aber, als sie daselbst waren, erfüllten sich die Tage, dass sie gebären sollte. Und sie gebar ihren erstgeborenen Sohn, und wickelte ihn in Windeln, und legte ihn in eine Krippe, weil für sie kein Platz war in der Herberge.»",
			"verseData": {
				"book": "Lukas",
				"chapter": 2,
				"verses": [
					{
						"verse": 1,
						"text": "Es geschah aber in denselben Tagen, dass vom Kaiser Augustus ein Befehl ausging, dass der ganze Erdkreis aufgeschrieben werde."
					},
					{
						"verse": 2,
						"text": "Diese Aufschreibung war die erste, und geschah durch Cyrinus, den Statthalter von Syrien."
					},
					{
						"verse": 3,
						"text": "Und alle gingen hin, sich aufschreiben zu lassen, ein jeder in seine Stadt."
					},
					{
						"verse": 4,
						"text": "Da zog auch Joseph von Galiläa, aus der Stadt Nazareth, hinauf nach Judäa in die Stadt Davids, welche Bethlehem heißt, weil er aus dem Hause und Geschlechte Davids war,"
					},
					{
						"verse": 5,
						"text": "um sich aufschreiben zu lassen mit Maria, seinem verlobten Weibe, welche schwanger war,"
					},
					{
						"verse": 6,
						"text": "Es begab sich aber, als sie daselbst waren, erfüllten sich die Tage, dass sie gebären sollte."
					},
					{
						"verse": 7,
						"text": "Und sie gebar ihren erstgeborenen Sohn, und wickelte ihn in Windeln, und legte ihn in eine Krippe, weil für sie kein Platz war in der Herberge."
					}
				]
			}
		},
		{
			"title": "Das vierte freudenreiche Geheimnis: Jesus wird von Maria und Josef im Tempel dargebracht.",
			"reference": "Lk 2, 21-24",
			"text": "«Und nachdem acht Tage um waren, und das Kind beschnitten werden sollte, ward sein Name Jesus genannt, wie ihn schon der Engel genannt hatte, ehe er empfangen ward. Da nun die Tage ihrer Reinigung nach dem Gesetze Moses erfüllt waren, brachten sie ihn nach Jerusalem, um ihn dem Herrn darzustellen; wie geschrieben steht im Gesetze des Herrn: Jede männliche Erstgeburt soll dem Herrn geheiligt werden; und um ein Opfer darzubringen, wie es dem Gesetze des Herrn geboten ist, ein Paar Turteltauben, oder zwei junge Tauben.»",
			"verseData": {
				"book": "Lukas",
				"chapter": 2,
				"verses": [
					{
						"verse": 21,
						"text": "Und nachdem acht Tage um waren, und das Kind beschnitten werden sollte, ward sein Name Jesus genannt, wie ihn schon der Engel genannt hatte, ehe er empfangen ward."
					},
					{
						"verse": 22,
						"text": "Da nun die Tage ihrer Reinigung nach dem Gesetze Moses erfüllt waren, brachten sie ihn nach Jerusalem, um ihn dem Herrn darzustellen;"
					},
					{
						"verse": 23,
						"text": "wie geschrieben steht im Gesetze des Herrn: Jede männliche Erstgeburt soll dem Herrn geheiligt werden;"
					},
					{
						"verse": 24,
						"text": "und um ein Opfer darzubringen, wie es dem Gesetze des Herrn geboten ist, ein Paar Turteltauben, oder zwei junge Tauben."
					}
				]
			}
		},
		{
			"title": "Das fünfte freudenreiche Geheimnis: Jesus wird im Tempel wiedergefunden.",
			"reference": "Lk 2, 41-47",
			"text": "«Und seine Eltern gingen alle Jahre nach Jerusalem am Osterfeste. Als er nun zwölf Jahre alt war, gingen sie nach der Gewohnheit des Festtages nach Jerusalem hinauf. Und da sie am Ende der Festtage wieder zurückkehrten, blieb der Knabe Jesus in Jerusalem, ohne dass es seine Eltern wussten. Da sie aber meinten, er sei bei der Reisegesellschaft, gingen sie eine Tagreise weit, und suchten ihn unter den Verwandten und Bekannten. Und da sie ihn nicht fanden, kehrten sie nach Jerusalem zurück, ihn suchend. Und es geschah, nach drei Tagen fanden sie ihn im Tempel, wie er unter den Lehrern saß und ihnen zuhörte, und sie befragte. Es staunten aber alle, die ihn hörten, über seine Einsicht und seine Antworten.»",
			"verseData": {
				"book": "Lukas",
				"chapter": 2,
				"verses": [
					{
						"verse": 41,
						"text": "Und seine Eltern gingen alle Jahre nach Jerusalem am Osterfeste."
					},
					{
						"verse": 42,
						"text": "Als er nun zwölf Jahre alt war, gingen sie nach der Gewohnheit des Festtages nach Jerusalem hinauf."
					},
					{
						"verse": 43,
						"text": "Und da sie am Ende der Festtage wieder zurückkehrten, blieb der Knabe Jesus in Jerusalem, ohne dass es seine Eltern wussten."
					},
					{
						"verse": 44,
						"text": "Da sie aber meinten, er sei bei der Reisegesellschaft, gingen sie eine Tagreise weit, und suchten ihn unter den Verwandten und Bekannten."
					},
					{
						"verse": 45,
						"text": "Und da sie ihn nicht fanden, kehrten sie nach Jerusalem zurück, ihn suchend."
					},
					{
						"verse": 46,
						"text": "Und es geschah, nach drei Tagen fanden sie ihn im Tempel, wie er unter den Lehrern saß und ihnen zuhörte, und sie befragte."
					},
					{
						"verse": 47,
						"text": "Es staunten aber alle, die ihn hörten, über seine Einsicht und seine Antworten."
					}
				]
			}
		}
	],
	"schmerzhaften": [
		{
			"title": "Das erste schmerzhafte Geheimnis: Die Todesangst Jesu.",
			"reference": "Mt 26, 36-39",
			"text": "«Da kam Jesus mit ihnen in einen Meierhog, Gethsemani genannt, und sprach zu seinen Jüngern: Setzet euch hier, während ich dorthin gehe und bete. Und er nahm den Petrus und die zwei Söhne des Zebedäus mit sich, und fing an, sich zu betrüben und zu bangen. Da sprach er zu ihnen: Meine Seele ist betrübt bis in den Tod, bleibet hier und wachet mit mir! Und nachdem er ein wenig vorwärts gegangen war, fiel er auf sein Angesicht, betete, und sprach: Mein Vater! wenn es möglich ist, so gehe dieser Kelch an mir vorüber; jedoch nicht wie ich will, sondern wie du.»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 26,
				"verses": [
					{
						"verse": 36,
						"text": "Da kam Jesus mit ihnen in einen Meierhog, Gethsemani genannt, und sprach zu seinen Jüngern: Setzet euch hier, während ich dorthin gehe und bete."
					},
					{
						"verse": 37,
						"text": "Und er nahm den Petrus und die zwei Söhne des Zebedäus mit sich, und fing an, sich zu betrüben und zu bangen."
					},
					{
						"verse": 38,
						"text": "Da sprach er zu ihnen: Meine Seele ist betrübt bis in den Tod, bleibet hier und wachet mit mir!"
					},
					{
						"verse": 39,
						"text": "Und nachdem er ein wenig vorwärts gegangen war, fiel er auf sein Angesicht, betete, und sprach: Mein Vater! wenn es möglich ist, so gehe dieser Kelch an mir vorüber; jedoch nicht wie ich will, sondern wie du."
					}
				]
			}
		},
		{
			"title": "Das zweite schmerzhafte Geheimnis: Die Geißelung Jesu.",
			"reference": "Mt 27, 26",
			"text": "«Alsdann gab er ihnen den Barabbas frei; Jesus aber ließ er geißeln, und überlieferte ihnen denselben, damit er gekreuziget würde.»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 27,
				"verses": [
					{
						"verse": 26,
						"text": "Alsdann gab er ihnen den Barabbas frei; Jesus aber ließ er geißeln, und überlieferte ihnen denselben, damit er gekreuziget würde."
					}
				]
			}
		},
		{
			"title": "Das dritte schmerzhafte Geheimnis: Die Dornenkrönung.",
			"reference": "Mt 27, 27-29",
			"text": "«Da nahmen die Soldaten des Landpflegers Jesus zu sich hinein in das Richthaus, und versammelten um ihn die ganze Schar. Und sie zogen ihn aus, und legten ihm einen scharlachroten Mantel um, und flochten eine Krone aus Dornen, setzten sie auf sein Haupt, und gaben ihm ein Rohr in seine rechte Hand. Und sie bogen das Knie vor ihm, verspotteten ihn, und sprachen: Sei gegrüßt, König der Juden!»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 27,
				"verses": [
					{
						"verse": 27,
						"text": "Da nahmen die Soldaten des Landpflegers Jesus zu sich hinein in das Richthaus, und versammelten um ihn die ganze Schar."
					},
					{
						"verse": 28,
						"text": "Und sie zogen ihn aus, und legten ihm einen scharlachroten Mantel um,"
					},
					{
						"verse": 29,
						"text": "und flochten eine Krone aus Dornen, setzten sie auf sein Haupt, und gaben ihm ein Rohr in seine rechte Hand. Und sie bogen das Knie vor ihm, verspotteten ihn, und sprachen: Sei gegrüßt, König der Juden!"
					}
				]
			}
		},
		{
			"title": "Das vierte schmerzhafte Geheimnis: Jesus trägt das schwere Kreuz.",
			"reference": "Mk 15, 21-22",
			"text": "«Und sie zwangen einen Vorübergehenden, Simon von Zyrene, der vom Lande kam, den Vater des Alexander und Rufus, sein Kreuz auf sich zu nehmen. Und sie führten ihn an den Ort Golgotha, was verdolmetscht ist: Schädelstätte.»",
			"verseData": {
				"book": "Markus",
				"chapter": 15,
				"verses": [
					{
						"verse": 21,
						"text": "Und sie zwangen einen Vorübergehenden, Simon von Zyrene, der vom Lande kam, den Vater des Alexander und Rufus, sein Kreuz auf sich zu nehmen."
					},
					{
						"verse": 22,
						"text": "Und sie führten ihn an den Ort Golgotha, was verdolmetscht ist: Schädelstätte."
					}
				]
			}
		},
		{
			"title": "Das fünfte schmerzhafte Geheimnis: Die Kreuzigung Jesu.",
			"reference": "Lk 23, 33-46",
			"text": "«Und als sie an den Ort kamen, den man Schädelstätte heißt, kreuzigten sie ihn daselbst, und die Räuber, den einen zur Rechten, und den andern zur Linken. Jesus aber sprach: Vater! vergib ihnen; denn sie wissen nicht, was sie tun. Und sie teilten seine Kleider unter sich, das Los darüber werfend. Und das Volk stand da und schaute zu. Und die Vorsteher verlachten ihn mit ihnen, und sprachen: Anderen hat er geholfen, er helfe sich selbst, wenn er Christus, der Auserwählte Gottes ist! Es verspotteten ihn aber auch die Soldaten, welche hinzutraten, ihm Essig reichten, und sprachen: Bist du der König der Juden, so hilf dir! Es war aber auch die Aufschrift über ihm geschrieben in griechischer, lateinischer und hebräischer Schrift: Dies ist der König der Juden. Einer aber von den Übeltätern, die am Kreuze hingen, lästerte ihn, und sprach: Wenn du Christus bist, so hilf dir selber und uns! Da antwortete der andere, verwies es ihm, und sprach: Fürchtest auch du Gott nicht, da du doch dieselbe Strafe erleidest? Und wir zwar mit Recht, denn wir empfangen, was unsere Taten verdient haben; dieser aber hat nichts Böses getan. Und er sprach zu Jesus: Herr! gedenke meiner, wenn du in dein Reich kommst. Jesus sprach zu ihm: Wahrlich, ich sage dir, heute wirst du mit mir im Paradiese sein! Es war aber um die sechste Stunde, da ward eine Finsternis über die ganze Erde bis zur neunten Stunde. Die Sonne verfinsterte sich, und der Vorhang des Tempels riss mitten entzwei. Und Jesus rief mit lauter Stimme, und sprach: Vater, in deine Hände empfehle ich meinen Geist. Und indem er dies sagte, verschied er.»",
			"verseData": {
				"book": "Lukas",
				"chapter": 23,
				"verses": [
					{
						"verse": 33,
						"text": "Und als sie an den Ort kamen, den man Schädelstätte heißt, kreuzigten sie ihn daselbst, und die Räuber, den einen zur Rechten, und den andern zur Linken."
					},
					{
						"verse": 34,
						"text": "Jesus aber sprach: Vater! vergib ihnen; denn sie wissen nicht, was sie tun. Und sie teilten seine Kleider unter sich, das Los darüber werfend."
					},
					{
						"verse": 35,
						"text": "Und das Volk stand da und schaute zu. Und die Vorsteher verlachten ihn mit ihnen, und sprachen: Anderen hat er geholfen, er helfe sich selbst, wenn er Christus, der Auserwählte Gottes ist!"
					},
					{
						"verse": 36,
						"text": "Es verspotteten ihn aber auch die Soldaten, welche hinzutraten, ihm Essig reichten,"
					},
					{
						"verse": 37,
						"text": "und sprachen: Bist du der König der Juden, so hilf dir!"
					},
					{
						"verse": 38,
						"text": "Es war aber auch die Aufschrift über ihm geschrieben in griechischer, lateinischer und hebräischer Schrift: Dies ist der König der Juden."
					},
					{
						"verse": 39,
						"text": "Einer aber von den Übeltätern, die am Kreuze hingen, lästerte ihn, und sprach: Wenn du Christus bist, so hilf dir selber und uns!"
					},
					{
						"verse": 40,
						"text": "Da antwortete der andere, verwies es ihm, und sprach: Fürchtest auch du Gott nicht, da du doch dieselbe Strafe erleidest?"
					},
					{
						"verse": 41,
						"text": "Und wir zwar mit Recht, denn wir empfangen, was unsere Taten verdient haben; dieser aber hat nichts Böses getan."
					},
					{
						"verse": 42,
						"text": "Und er sprach zu Jesus: Herr! gedenke meiner, wenn du in dein Reich kommst."
					},
					{
						"verse": 43,
						"text": "Jesus sprach zu ihm: Wahrlich, ich sage dir, heute wirst du mit mir im Paradiese sein!"
					},
					{
						"verse": 44,
						"text": "Es war aber um die sechste Stunde, da ward eine Finsternis über die ganze Erde bis zur neunten Stunde."
					},
					{
						"verse": 45,
						"text": "Die Sonne verfinsterte sich, und der Vorhang des Tempels riss mitten entzwei."
					},
					{
						"verse": 46,
						"text": "Und Jesus rief mit lauter Stimme, und sprach: Vater, in deine Hände empfehle ich meinen Geist. Und indem er dies sagte, verschied er."
					}
				]
			}
		}
	],
	"glorreichen": [
		{
			"title": "Das erste glorreiche Geheimnis: Die Auferstehung Jesu.",
			"reference": "Lk 24, 1-6",
			"text": "«Am ersten Tage der Woche aber kamen sie am frühesten Morgen zum Grabe, und brachten die Spezereien, welche sie bereitet hatten. Da fanden sie den Stein vom Grabe weggewälzt. Und sie gingen hinein, fanden aber den Leib des Herrn Jesus nicht. Und es geschah, während sie im Gemüte darüber bestürzt waren, siehe, standen zwei Männer in glänzenden Kleidern neben ihnen. Da sie nun erschracken, und ihr Angesicht zur Erde senkten, sprachen jene zu ihnen: Was suchet ihr den Lebenden bei den Toten? Er ist nicht hier, sondern ist auferstanden. Erinnert euch, wie er zu euch geredet hat, als er noch in Galiläa war,»",
			"verseData": {
				"book": "Lukas",
				"chapter": 24,
				"verses": [
					{
						"verse": 1,
						"text": "Am ersten Tage der Woche aber kamen sie am frühesten Morgen zum Grabe, und brachten die Spezereien, welche sie bereitet hatten."
					},
					{
						"verse": 2,
						"text": "Da fanden sie den Stein vom Grabe weggewälzt."
					},
					{
						"verse": 3,
						"text": "Und sie gingen hinein, fanden aber den Leib des Herrn Jesus nicht."
					},
					{
						"verse": 4,
						"text": "Und es geschah, während sie im Gemüte darüber bestürzt waren, siehe, standen zwei Männer in glänzenden Kleidern neben ihnen."
					},
					{
						"verse": 5,
						"text": "Da sie nun erschracken, und ihr Angesicht zur Erde senkten, sprachen jene zu ihnen: Was suchet ihr den Lebenden bei den Toten?"
					},
					{
						"verse": 6,
						"text": "Er ist nicht hier, sondern ist auferstanden. Erinnert euch, wie er zu euch geredet hat, als er noch in Galiläa war,"
					}
				]
			}
		},
		{
			"title": "Das zweite glorreiche Geheimnis: Die Himmerfahrt Jesu.",
			"reference": "Mk 16, 19",
			"text": "«Und nachdem der Herr Jesus zu ihnen gesprochen hatte, ward er in den Himmel aufgenommen, und sitzet zur Rechten Gottes.»",
			"verseData": {
				"book": "Markus",
				"chapter": 16,
				"verses": [
					{
						"verse": 19,
						"text": "Und nachdem der Herr Jesus zu ihnen gesprochen hatte, ward er in den Himmel aufgenommen, und sitzet zur Rechten Gottes."
					}
				]
			}
		},
		{
			"title": "Das dritte glorreiche Geheimnis: Die Herabkunft des Heiligen Geistes im Abendmahlssaal.",
			"reference": "Apg 2, 1-4",
			"text": "«Als der Tag des Pfingstfestes gekommen war, waren alle einmütig an demselben Orte. Da entstand plötzlich vom Himmel herab ein Brausen, gleich dem eines daherfahrenden gewaltigen Windes, und erfüllte das ganze Haus, wo sie saßen. Und es erschienen ihnen zerteilte Zungen wie von Feuer, und es ließ sich auf einen jeden von ihnen nieder. Und es wurden alle mit dem Heiligen Geiste erfüllet, und fingen an, in verschiedenen Sprachen zu reden, so wie der Heilige Geist ihnen verlieh auszusprechen.»",
			"verseData": {
				"book": "Apostelgeschichte",
				"chapter": 2,
				"verses": [
					{
						"verse": 1,
						"text": "Als der Tag des Pfingstfestes gekommen war, waren alle einmütig an demselben Orte."
					},
					{
						"verse": 2,
						"text": "Da entstand plötzlich vom Himmel herab ein Brausen, gleich dem eines daherfahrenden gewaltigen Windes, und erfüllte das ganze Haus, wo sie saßen."
					},
					{
						"verse": 3,
						"text": "Und es erschienen ihnen zerteilte Zungen wie von Feuer, und es ließ sich auf einen jeden von ihnen nieder."
					},
					{
						"verse": 4,
						"text": "Und es wurden alle mit dem Heiligen Geiste erfüllet, und fingen an, in verschiedenen Sprachen zu reden, so wie der Heilige Geist ihnen verlieh auszusprechen."
					}
				]
			}
		},
		{
			"title": "Das vierte glorreiche Geheimnis: Die Aufnahme Marias in den Himmel.",
			"reference": "Lk 1, 48-49",
			"text": "«Weil er die Niedrigkeit seiner Magd angesehen hat; denn siehe, von nun an werden mich selig preisen alle Geschlechter. Denn Großes hat an mir getan, der mächtig, und dessen Name heilig ist!»",
			"verseData": {
				"book": "Lukas",
				"chapter": 1,
				"verses": [
					{
						"verse": 48,
						"text": "Weil er die Niedrigkeit seiner Magd angesehen hat; denn siehe, von nun an werden mich selig preisen alle Geschlechter."
					},
					{
						"verse": 49,
						"text": "Denn Großes hat an mir getan, der mächtig, und dessen Name heilig ist!"
					}
				]
			}
		},
		{
			"title": "Das fünfte glorreiche Geheimnis: Die Krönung Marias zur Königin des Himmels und der Erde.",
			"reference": "Offb 12, 1",
			"text": "«Und es erschien ein großes Zeichen im Himmel: Ein Weib mit der Sonne bekleidet, den Mond unter ihren Füßen, und auf ihrem Haupte eine Krone von zwölf Sternen.»",
			"verseData": {
				"book": "Offenbarung",
				"chapter": 12,
				"verses": [
					{
						"verse": 1,
						"text": "Und es erschien ein großes Zeichen im Himmel: Ein Weib mit der Sonne bekleidet, den Mond unter ihren Füßen, und auf ihrem Haupte eine Krone von zwölf Sternen."
					}
				]
			}
		}
	]
};
