// Auto-generated by scripts/generate-mystery-verses.ts — do not edit manually
import type { MysteryDescription } from './mysteryDescriptions';

export const mysteryVerseDataDe: Record<string, MysteryDescription[]> = {
	"lichtreichen": [
		{
			"title": "Das erste lichtreiche Geheimnis: Die Taufe im Jordan.",
			"reference": "Mt 3, 16-17",
			"text": "«Als aber Jesus getauft war, stieg er sogleich aus dem Wasser heraus; und siehe, es öffneten sich ihm die Himmel, und er sah den Geist Gottes herabkommen über ihn und wie eine Taube herabsteigen. Und siehe, eine Stimme vom Himmel sprach: Dieser ist mein Sohn, der geliebte, an welchem ich Wohlgefallen habe!»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 3,
				"verses": [
					{
						"verse": 16,
						"text": "Als aber Jesus getauft war, stieg er sogleich aus dem Wasser heraus; und siehe, es öffneten sich ihm die Himmel, und er sah den Geist Gottes herabkommen über ihn und wie eine Taube herabsteigen."
					},
					{
						"verse": 17,
						"text": "Und siehe, eine Stimme vom Himmel sprach: Dieser ist mein Sohn, der geliebte, an welchem ich Wohlgefallen habe!"
					}
				]
			}
		},
		{
			"title": "Das zweite lichtreiche Geheimnis: Die Hochzeit von Kana.",
			"reference": "Joh 2, 1-5",
			"text": "«Am dritten Tage ward eine Hochzeit gehalten zu Kana in Galiläa; und die Mutter Jesu war dabei. Auch Jesus und seine Jünger waren zur Hochzeit geladen. Und da der Wein ausging, sagte die Mutter Jesu zu ihm: Sie haben keinen Wein! Jesus aber sprach zu ihr: Weib! was soll dies mir und dir? Noch ist meine Stunde nicht gekommen. Da sagte seine Mutter zu den Dienern: Was immer er euch sagt, das tut!»",
			"verseData": {
				"book": "Johannes",
				"chapter": 2,
				"verses": [
					{
						"verse": 1,
						"text": "Am dritten Tage ward eine Hochzeit gehalten zu Kana in Galiläa; und die Mutter Jesu war dabei."
					},
					{
						"verse": 2,
						"text": "Auch Jesus und seine Jünger waren zur Hochzeit geladen."
					},
					{
						"verse": 3,
						"text": "Und da der Wein ausging, sagte die Mutter Jesu zu ihm: Sie haben keinen Wein!"
					},
					{
						"verse": 4,
						"text": "Jesus aber sprach zu ihr: Weib! was soll dies mir und dir? Noch ist meine Stunde nicht gekommen."
					},
					{
						"verse": 5,
						"text": "Da sagte seine Mutter zu den Dienern: Was immer er euch sagt, das tut!"
					}
				]
			}
		},
		{
			"title": "Das dritte lichtreiche Geheimnis: Die Verkündigung des Reiches Gottes.",
			"reference": "Mk 1, 15",
			"text": "«und sprach: Erfüllet ist die Zeit, und das Reich Gottes hat sich genahet; tuet Buße und dem Evangelium!»",
			"verseData": {
				"book": "Markus",
				"chapter": 1,
				"verses": [
					{
						"verse": 15,
						"text": "und sprach: Erfüllet ist die Zeit, und das Reich Gottes hat sich genahet; tuet Buße und dem Evangelium!"
					}
				]
			}
		},
		{
			"title": "Das vierte lichtreiche Geheimnis: Die Verklärung.",
			"reference": "Mt 17, 1-2",
			"text": "«Nach sechs Tagen nahm Jesus den Petrus, Jakobus und Johannes, Bruder desselben, zu sich, und führte sie allein auf einen hohen Berg. Und er ward vor ihnen verklärt; und sein Angesicht leuchtete wie die Sonne, seine Kleider aber wurden weiß wie der Schnee.»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 17,
				"verses": [
					{
						"verse": 1,
						"text": "Nach sechs Tagen nahm Jesus den Petrus, Jakobus und Johannes, Bruder desselben, zu sich, und führte sie allein auf einen hohen Berg."
					},
					{
						"verse": 2,
						"text": "Und er ward vor ihnen verklärt; und sein Angesicht leuchtete wie die Sonne, seine Kleider aber wurden weiß wie der Schnee."
					}
				]
			}
		},
		{
			"title": "Das fünfte lichtreiche Geheimnis: Die heiligste Eucharistie (Das Altarssakrament).",
			"reference": "Mt 26, 26",
			"text": "«Während sie aber aßen, nahm Jesus Brot, segnete und brach es, gab es seinen Jüngern, und sprach: Nehmet hin, und esset, dies ist mein Leib!»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 26,
				"verses": [
					{
						"verse": 26,
						"text": "Während sie aber aßen, nahm Jesus Brot, segnete und brach es, gab es seinen Jüngern, und sprach: Nehmet hin, und esset, dies ist mein Leib!"
					}
				]
			}
		}
	],
	"freudenreich": [
		{
			"title": "Das erste freudenreiche Geheimnis: Die Verkündigung des Erzengles Gabriel an die Jungfrau Maria.",
			"reference": "Lk 1, 26-27",
			"text": "«Im sechsten Monate aber ward der Engel Gabriel von Gott gesandt in eine Stadt in Galiläa, mit Namen Nazareth, zu einer Jungfrau, die verlobt war mit einem Manne, mit Namen Joseph, vom Hause Davids, und der Name der Jungfrau war Maria.»",
			"verseData": {
				"book": "Lukas",
				"chapter": 1,
				"verses": [
					{
						"verse": 26,
						"text": "Im sechsten Monate aber ward der Engel Gabriel von Gott gesandt in eine Stadt in Galiläa, mit Namen Nazareth,"
					},
					{
						"verse": 27,
						"text": "zu einer Jungfrau, die verlobt war mit einem Manne, mit Namen Joseph, vom Hause Davids, und der Name der Jungfrau war Maria."
					}
				]
			}
		},
		{
			"title": "Das zweite freudenreiche Geheimnis: Der Besuch Marias bei Elisabeth.",
			"reference": "Lk 1, 39-42",
			"text": "«Maria aber machte sich in jenen Tagen auf, und ging eilends auf das Gebirge nach einer Stadt des Stammes Juda. Und sie kam in das Haus des Zacharias, und grüßte Elisabeth. Und es bagab sich, sobald Elisabeth den Gruß Marias hörte, hüpfte das Kind freudig in ihrem Leibe auf, und Elisabeth ward erfüllet von dem heiligen Geiste. Und sie rief mit lauter Stimme, und sprach: Gebenedeit bist du unter den Weibern, und gebenedeiet ist die Frucht deines Leibes!»",
			"verseData": {
				"book": "Lukas",
				"chapter": 1,
				"verses": [
					{
						"verse": 39,
						"text": "Maria aber machte sich in jenen Tagen auf, und ging eilends auf das Gebirge nach einer Stadt des Stammes Juda."
					},
					{
						"verse": 40,
						"text": "Und sie kam in das Haus des Zacharias, und grüßte Elisabeth."
					},
					{
						"verse": 41,
						"text": "Und es bagab sich, sobald Elisabeth den Gruß Marias hörte, hüpfte das Kind freudig in ihrem Leibe auf, und Elisabeth ward erfüllet von dem heiligen Geiste."
					},
					{
						"verse": 42,
						"text": "Und sie rief mit lauter Stimme, und sprach: Gebenedeit bist du unter den Weibern, und gebenedeiet ist die Frucht deines Leibes!"
					}
				]
			}
		},
		{
			"title": "Das dritte freudenreiche Geheimnis: Die Geburt Jesu im Stall von Bethlehem.",
			"reference": "Lk 2, 1-7",
			"text": "«Es geschah aber in denselben Tagen, dass vom Kaiser Augustus ein Befehl ausging, dass der ganze Erdkreis aufgeschrieben werde. Diese Aufschreibung war die erste, und geschah durch Cyrinus, den Statthalter von Syrien. Und alle gingen hin, sich aufschreiben zu lassen, ein jeder in seine Stadt. Da zog auch Joseph von Galiläa, aus der Stadt Nazareth, hinauf nach Judäa in die Stadt Davids, welche Bethlehem heißt, weil er aus dem Hause und Geschlechte Davids war, um sich aufschreiben zu lassen mit Maria, seinem verlobten Weibe, welche schwanger war, Es begab sich aber, als sie daselbst waren, erfüllten sich die Tage, dass sie gebären sollte. Und sie gebar ihren erstgeborenen Sohn, und wickelte ihn in Windeln, und legte ihn in eine Krippe, weil für sie kein Platz war in der Herberge.»",
			"verseData": {
				"book": "Lukas",
				"chapter": 2,
				"verses": [
					{
						"verse": 1,
						"text": "Es geschah aber in denselben Tagen, dass vom Kaiser Augustus ein Befehl ausging, dass der ganze Erdkreis aufgeschrieben werde."
					},
					{
						"verse": 2,
						"text": "Diese Aufschreibung war die erste, und geschah durch Cyrinus, den Statthalter von Syrien."
					},
					{
						"verse": 3,
						"text": "Und alle gingen hin, sich aufschreiben zu lassen, ein jeder in seine Stadt."
					},
					{
						"verse": 4,
						"text": "Da zog auch Joseph von Galiläa, aus der Stadt Nazareth, hinauf nach Judäa in die Stadt Davids, welche Bethlehem heißt, weil er aus dem Hause und Geschlechte Davids war,"
					},
					{
						"verse": 5,
						"text": "um sich aufschreiben zu lassen mit Maria, seinem verlobten Weibe, welche schwanger war,"
					},
					{
						"verse": 6,
						"text": "Es begab sich aber, als sie daselbst waren, erfüllten sich die Tage, dass sie gebären sollte."
					},
					{
						"verse": 7,
						"text": "Und sie gebar ihren erstgeborenen Sohn, und wickelte ihn in Windeln, und legte ihn in eine Krippe, weil für sie kein Platz war in der Herberge."
					}
				]
			}
		},
		{
			"title": "Das vierte freudenreiche Geheimnis: Jesus wird von Maria und Josef im Tempel dargebracht.",
			"reference": "Lk 2, 21-24",
			"text": "«Und nachdem acht Tage um waren, und das Kind beschnitten werden sollte, ward sein Name Jesus genannt, wie ihn schon der Engel genannt hatte, ehe er empfangen ward. Da nun die Tage ihrer Reinigung nach dem Gesetze Moses erfüllt waren, brachten sie ihn nach Jerusalem, um ihn dem Herrn darzustellen; wie geschrieben steht im Gesetze des Herrn: Jede männliche Erstgeburt soll dem Herrn geheiligt werden; und um ein Opfer darzubringen, wie es dem Gesetze des Herrn geboten ist, ein Paar Turteltauben, oder zwei junge Tauben.»",
			"verseData": {
				"book": "Lukas",
				"chapter": 2,
				"verses": [
					{
						"verse": 21,
						"text": "Und nachdem acht Tage um waren, und das Kind beschnitten werden sollte, ward sein Name Jesus genannt, wie ihn schon der Engel genannt hatte, ehe er empfangen ward."
					},
					{
						"verse": 22,
						"text": "Da nun die Tage ihrer Reinigung nach dem Gesetze Moses erfüllt waren, brachten sie ihn nach Jerusalem, um ihn dem Herrn darzustellen;"
					},
					{
						"verse": 23,
						"text": "wie geschrieben steht im Gesetze des Herrn: Jede männliche Erstgeburt soll dem Herrn geheiligt werden;"
					},
					{
						"verse": 24,
						"text": "und um ein Opfer darzubringen, wie es dem Gesetze des Herrn geboten ist, ein Paar Turteltauben, oder zwei junge Tauben."
					}
				]
			}
		},
		{
			"title": "Das fünfte freudenreiche Geheimnis: Jesus wird im Tempel wiedergefunden.",
			"reference": "Lk 2, 41-47",
			"text": "«Und seine Eltern gingen alle Jahre nach Jerusalem am Osterfeste. Als er nun zwölf Jahre alt war, gingen sie nach der Gewohnheit des Festtages nach Jerusalem hinauf. Und da sie am Ende der Festtage wieder zurückkehrten, blieb der Knabe Jesus in Jerusalem, ohne dass es seine Eltern wussten. Da sie aber meinten, er sei bei der Reisegesellschaft, gingen sie eine Tagreise weit, und suchten ihn unter den Verwandten und Bekannten. Und da sie ihn nicht fanden, kehrten sie nach Jerusalem zurück, ihn suchend. Und es geschah, nach drei Tagen fanden sie ihn im Tempel, wie er unter den Lehrern saß und ihnen zuhörte, und sie befragte. Es staunten aber alle, die ihn hörten, über seine Einsicht und seine Antworten.»",
			"verseData": {
				"book": "Lukas",
				"chapter": 2,
				"verses": [
					{
						"verse": 41,
						"text": "Und seine Eltern gingen alle Jahre nach Jerusalem am Osterfeste."
					},
					{
						"verse": 42,
						"text": "Als er nun zwölf Jahre alt war, gingen sie nach der Gewohnheit des Festtages nach Jerusalem hinauf."
					},
					{
						"verse": 43,
						"text": "Und da sie am Ende der Festtage wieder zurückkehrten, blieb der Knabe Jesus in Jerusalem, ohne dass es seine Eltern wussten."
					},
					{
						"verse": 44,
						"text": "Da sie aber meinten, er sei bei der Reisegesellschaft, gingen sie eine Tagreise weit, und suchten ihn unter den Verwandten und Bekannten."
					},
					{
						"verse": 45,
						"text": "Und da sie ihn nicht fanden, kehrten sie nach Jerusalem zurück, ihn suchend."
					},
					{
						"verse": 46,
						"text": "Und es geschah, nach drei Tagen fanden sie ihn im Tempel, wie er unter den Lehrern saß und ihnen zuhörte, und sie befragte."
					},
					{
						"verse": 47,
						"text": "Es staunten aber alle, die ihn hörten, über seine Einsicht und seine Antworten."
					}
				]
			}
		}
	],
	"schmerzhaften": [
		{
			"title": "Das erste schmerzhafte Geheimnis: Die Todesangst Jesu.",
			"reference": "Mt 26, 36-39",
			"text": "«Da kam Jesus mit ihnen in einen Meierhog, Gethsemani genannt, und sprach zu seinen Jüngern: Setzet euch hier, während ich dorthin gehe und bete. Und er nahm den Petrus und die zwei Söhne des Zebedäus mit sich, und fing an, sich zu betrüben und zu bangen. Da sprach er zu ihnen: Meine Seele ist betrübt bis in den Tod, bleibet hier und wachet mit mir! Und nachdem er ein wenig vorwärts gegangen war, fiel er auf sein Angesicht, betete, und sprach: Mein Vater! wenn es möglich ist, so gehe dieser Kelch an mir vorüber; jedoch nicht wie ich will, sondern wie du.»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 26,
				"verses": [
					{
						"verse": 36,
						"text": "Da kam Jesus mit ihnen in einen Meierhog, Gethsemani genannt, und sprach zu seinen Jüngern: Setzet euch hier, während ich dorthin gehe und bete."
					},
					{
						"verse": 37,
						"text": "Und er nahm den Petrus und die zwei Söhne des Zebedäus mit sich, und fing an, sich zu betrüben und zu bangen."
					},
					{
						"verse": 38,
						"text": "Da sprach er zu ihnen: Meine Seele ist betrübt bis in den Tod, bleibet hier und wachet mit mir!"
					},
					{
						"verse": 39,
						"text": "Und nachdem er ein wenig vorwärts gegangen war, fiel er auf sein Angesicht, betete, und sprach: Mein Vater! wenn es möglich ist, so gehe dieser Kelch an mir vorüber; jedoch nicht wie ich will, sondern wie du."
					}
				]
			}
		},
		{
			"title": "Das zweite schmerzhafte Geheimnis: Die Geißelung Jesu.",
			"reference": "Mt 27, 26",
			"text": "«Alsdann gab er ihnen den Barabbas frei; Jesus aber ließ er geißeln, und überlieferte ihnen denselben, damit er gekreuziget würde.»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 27,
				"verses": [
					{
						"verse": 26,
						"text": "Alsdann gab er ihnen den Barabbas frei; Jesus aber ließ er geißeln, und überlieferte ihnen denselben, damit er gekreuziget würde."
					}
				]
			}
		},
		{
			"title": "Das dritte schmerzhafte Geheimnis: Die Dornenkrönung.",
			"reference": "Mt 27, 27-29",
			"text": "«Da nahmen die Soldaten des Landpflegers Jesus zu sich hinein in das Richthaus, und versammelten um ihn die ganze Schar. Und sie zogen ihn aus, und legten ihm einen scharlachroten Mantel um, und flochten eine Krone aus Dornen, setzten sie auf sein Haupt, und gaben ihm ein Rohr in seine rechte Hand. Und sie bogen das Knie vor ihm, verspotteten ihn, und sprachen: Sei gegrüßt, König der Juden!»",
			"verseData": {
				"book": "Matthäus",
				"chapter": 27,
				"verses": [
					{
						"verse": 27,
						"text": "Da nahmen die Soldaten des Landpflegers Jesus zu sich hinein in das Richthaus, und versammelten um ihn die ganze Schar."
					},
					{
						"verse": 28,
						"text": "Und sie zogen ihn aus, und legten ihm einen scharlachroten Mantel um,"
					},
					{
						"verse": 29,
						"text": "und flochten eine Krone aus Dornen, setzten sie auf sein Haupt, und gaben ihm ein Rohr in seine rechte Hand. Und sie bogen das Knie vor ihm, verspotteten ihn, und sprachen: Sei gegrüßt, König der Juden!"
					}
				]
			}
		},
		{
			"title": "Das vierte schmerzhafte Geheimnis: Jesus trägt das schwere Kreuz.",
			"reference": "Mk 15, 21-22",
			"text": "«Und sie zwangen einen Vorübergehenden, Simon von Zyrene, der vom Lande kam, den Vater des Alexander und Rufus, sein Kreuz auf sich zu nehmen. Und sie führten ihn an den Ort Golgotha, was verdolmetscht ist: Schädelstätte.»",
			"verseData": {
				"book": "Markus",
				"chapter": 15,
				"verses": [
					{
						"verse": 21,
						"text": "Und sie zwangen einen Vorübergehenden, Simon von Zyrene, der vom Lande kam, den Vater des Alexander und Rufus, sein Kreuz auf sich zu nehmen."
					},
					{
						"verse": 22,
						"text": "Und sie führten ihn an den Ort Golgotha, was verdolmetscht ist: Schädelstätte."
					}
				]
			}
		},
		{
			"title": "Das fünfte schmerzhafte Geheimnis: Die Kreuzigung Jesu.",
			"reference": "Lk 23, 33-46",
			"text": "«Und als sie an den Ort kamen, den man Schädelstätte heißt, kreuzigten sie ihn daselbst, und die Räuber, den einen zur Rechten, und den andern zur Linken. Jesus aber sprach: Vater! vergib ihnen; denn sie wissen nicht, was sie tun. Und sie teilten seine Kleider unter sich, das Los darüber werfend. Und das Volk stand da und schaute zu. Und die Vorsteher verlachten ihn mit ihnen, und sprachen: Anderen hat er geholfen, er helfe sich selbst, wenn er Christus, der Auserwählte Gottes ist! Es verspotteten ihn aber auch die Soldaten, welche hinzutraten, ihm Essig reichten, und sprachen: Bist du der König der Juden, so hilf dir! Es war aber auch die Aufschrift über ihm geschrieben in griechischer, lateinischer und hebräischer Schrift: Dies ist der König der Juden. Einer aber von den Übeltätern, die am Kreuze hingen, lästerte ihn, und sprach: Wenn du Christus bist, so hilf dir selber und uns! Da antwortete der andere, verwies es ihm, und sprach: Fürchtest auch du Gott nicht, da du doch dieselbe Strafe erleidest? Und wir zwar mit Recht, denn wir empfangen, was unsere Taten verdient haben; dieser aber hat nichts Böses getan. Und er sprach zu Jesus: Herr! gedenke meiner, wenn du in dein Reich kommst. Jesus sprach zu ihm: Wahrlich, ich sage dir, heute wirst du mit mir im Paradiese sein! Es war aber um die sechste Stunde, da ward eine Finsternis über die ganze Erde bis zur neunten Stunde. Die Sonne verfinsterte sich, und der Vorhang des Tempels riss mitten entzwei. Und Jesus rief mit lauter Stimme, und sprach: Vater, in deine Hände empfehle ich meinen Geist. Und indem er dies sagte, verschied er.»",
			"verseData": {
				"book": "Lukas",
				"chapter": 23,
				"verses": [
					{
						"verse": 33,
						"text": "Und als sie an den Ort kamen, den man Schädelstätte heißt, kreuzigten sie ihn daselbst, und die Räuber, den einen zur Rechten, und den andern zur Linken."
					},
					{
						"verse": 34,
						"text": "Jesus aber sprach: Vater! vergib ihnen; denn sie wissen nicht, was sie tun. Und sie teilten seine Kleider unter sich, das Los darüber werfend."
					},
					{
						"verse": 35,
						"text": "Und das Volk stand da und schaute zu. Und die Vorsteher verlachten ihn mit ihnen, und sprachen: Anderen hat er geholfen, er helfe sich selbst, wenn er Christus, der Auserwählte Gottes ist!"
					},
					{
						"verse": 36,
						"text": "Es verspotteten ihn aber auch die Soldaten, welche hinzutraten, ihm Essig reichten,"
					},
					{
						"verse": 37,
						"text": "und sprachen: Bist du der König der Juden, so hilf dir!"
					},
					{
						"verse": 38,
						"text": "Es war aber auch die Aufschrift über ihm geschrieben in griechischer, lateinischer und hebräischer Schrift: Dies ist der König der Juden."
					},
					{
						"verse": 39,
						"text": "Einer aber von den Übeltätern, die am Kreuze hingen, lästerte ihn, und sprach: Wenn du Christus bist, so hilf dir selber und uns!"
					},
					{
						"verse": 40,
						"text": "Da antwortete der andere, verwies es ihm, und sprach: Fürchtest auch du Gott nicht, da du doch dieselbe Strafe erleidest?"
					},
					{
						"verse": 41,
						"text": "Und wir zwar mit Recht, denn wir empfangen, was unsere Taten verdient haben; dieser aber hat nichts Böses getan."
					},
					{
						"verse": 42,
						"text": "Und er sprach zu Jesus: Herr! gedenke meiner, wenn du in dein Reich kommst."
					},
					{
						"verse": 43,
						"text": "Jesus sprach zu ihm: Wahrlich, ich sage dir, heute wirst du mit mir im Paradiese sein!"
					},
					{
						"verse": 44,
						"text": "Es war aber um die sechste Stunde, da ward eine Finsternis über die ganze Erde bis zur neunten Stunde."
					},
					{
						"verse": 45,
						"text": "Die Sonne verfinsterte sich, und der Vorhang des Tempels riss mitten entzwei."
					},
					{
						"verse": 46,
						"text": "Und Jesus rief mit lauter Stimme, und sprach: Vater, in deine Hände empfehle ich meinen Geist. Und indem er dies sagte, verschied er."
					}
				]
			}
		}
	],
	"glorreichen": [
		{
			"title": "Das erste glorreiche Geheimnis: Die Auferstehung Jesu.",
			"reference": "Lk 24, 1-6",
			"text": "«Am ersten Tage der Woche aber kamen sie am frühesten Morgen zum Grabe, und brachten die Spezereien, welche sie bereitet hatten. Da fanden sie den Stein vom Grabe weggewälzt. Und sie gingen hinein, fanden aber den Leib des Herrn Jesus nicht. Und es geschah, während sie im Gemüte darüber bestürzt waren, siehe, standen zwei Männer in glänzenden Kleidern neben ihnen. Da sie nun erschracken, und ihr Angesicht zur Erde senkten, sprachen jene zu ihnen: Was suchet ihr den Lebenden bei den Toten? Er ist nicht hier, sondern ist auferstanden. Erinnert euch, wie er zu euch geredet hat, als er noch in Galiläa war,»",
			"verseData": {
				"book": "Lukas",
				"chapter": 24,
				"verses": [
					{
						"verse": 1,
						"text": "Am ersten Tage der Woche aber kamen sie am frühesten Morgen zum Grabe, und brachten die Spezereien, welche sie bereitet hatten."
					},
					{
						"verse": 2,
						"text": "Da fanden sie den Stein vom Grabe weggewälzt."
					},
					{
						"verse": 3,
						"text": "Und sie gingen hinein, fanden aber den Leib des Herrn Jesus nicht."
					},
					{
						"verse": 4,
						"text": "Und es geschah, während sie im Gemüte darüber bestürzt waren, siehe, standen zwei Männer in glänzenden Kleidern neben ihnen."
					},
					{
						"verse": 5,
						"text": "Da sie nun erschracken, und ihr Angesicht zur Erde senkten, sprachen jene zu ihnen: Was suchet ihr den Lebenden bei den Toten?"
					},
					{
						"verse": 6,
						"text": "Er ist nicht hier, sondern ist auferstanden. Erinnert euch, wie er zu euch geredet hat, als er noch in Galiläa war,"
					}
				]
			}
		},
		{
			"title": "Das zweite glorreiche Geheimnis: Die Himmerfahrt Jesu.",
			"reference": "Mk 16, 19",
			"text": "«Und nachdem der Herr Jesus zu ihnen gesprochen hatte, ward er in den Himmel aufgenommen, und sitzet zur Rechten Gottes.»",
			"verseData": {
				"book": "Markus",
				"chapter": 16,
				"verses": [
					{
						"verse": 19,
						"text": "Und nachdem der Herr Jesus zu ihnen gesprochen hatte, ward er in den Himmel aufgenommen, und sitzet zur Rechten Gottes."
					}
				]
			}
		},
		{
			"title": "Das dritte glorreiche Geheimnis: Die Herabkunft des Heiligen Geistes im Abendmahlssaal.",
			"reference": "Apg 2, 1-4",
			"text": "«Als der Tag des Pfingstfestes gekommen war, waren alle einmütig an demselben Orte. Da entstand plötzlich vom Himmel herab ein Brausen, gleich dem eines daherfahrenden gewaltigen Windes, und erfüllte das ganze Haus, wo sie saßen. Und es erschienen ihnen zerteilte Zungen wie von Feuer, und es ließ sich auf einen jeden von ihnen nieder. Und es wurden alle mit dem Heiligen Geiste erfüllet, und fingen an, in verschiedenen Sprachen zu reden, so wie der Heilige Geist ihnen verlieh auszusprechen.»",
			"verseData": {
				"book": "Apostelgeschichte",
				"chapter": 2,
				"verses": [
					{
						"verse": 1,
						"text": "Als der Tag des Pfingstfestes gekommen war, waren alle einmütig an demselben Orte."
					},
					{
						"verse": 2,
						"text": "Da entstand plötzlich vom Himmel herab ein Brausen, gleich dem eines daherfahrenden gewaltigen Windes, und erfüllte das ganze Haus, wo sie saßen."
					},
					{
						"verse": 3,
						"text": "Und es erschienen ihnen zerteilte Zungen wie von Feuer, und es ließ sich auf einen jeden von ihnen nieder."
					},
					{
						"verse": 4,
						"text": "Und es wurden alle mit dem Heiligen Geiste erfüllet, und fingen an, in verschiedenen Sprachen zu reden, so wie der Heilige Geist ihnen verlieh auszusprechen."
					}
				]
			}
		},
		{
			"title": "Das vierte glorreiche Geheimnis: Die Aufnahme Marias in den Himmel.",
			"reference": "Lk 1, 48-49",
			"text": "«Weil er die Niedrigkeit seiner Magd angesehen hat; denn siehe, von nun an werden mich selig preisen alle Geschlechter. Denn Großes hat an mir getan, der mächtig, und dessen Name heilig ist!»",
			"verseData": {
				"book": "Lukas",
				"chapter": 1,
				"verses": [
					{
						"verse": 48,
						"text": "Weil er die Niedrigkeit seiner Magd angesehen hat; denn siehe, von nun an werden mich selig preisen alle Geschlechter."
					},
					{
						"verse": 49,
						"text": "Denn Großes hat an mir getan, der mächtig, und dessen Name heilig ist!"
					}
				]
			}
		},
		{
			"title": "Das fünfte glorreiche Geheimnis: Die Krönung Marias zur Königin des Himmels und der Erde.",
			"reference": "Offb 12, 1",
			"text": "«Und es erschien ein großes Zeichen im Himmel: Ein Weib mit der Sonne bekleidet, den Mond unter ihren Füßen, und auf ihrem Haupte eine Krone von zwölf Sternen.»",
			"verseData": {
				"book": "Offenbarung",
				"chapter": 12,
				"verses": [
					{
						"verse": 1,
						"text": "Und es erschien ein großes Zeichen im Himmel: Ein Weib mit der Sonne bekleidet, den Mond unter ihren Füßen, und auf ihrem Haupte eine Krone von zwölf Sternen."
					}
				]
			}
		}
	]
};

export const mysteryVerseDataEn: Record<string, MysteryDescription[]> = {
	"lichtreichen": [
		{
			"title": "The first Luminous Mystery: The Baptism in the Jordan.",
			"reference": "Mt 3:16-17",
			"text": "«And Jesus being baptized, forthwith came out of the water: and lo, the heavens were opened to him: and he saw the Spirit of God descending as a dove, and coming upon him. And behold a voice from heaven saying: This is my beloved Son, in whom I am well pleased.»",
			"verseData": {
				"book": "Matthew",
				"chapter": 3,
				"verses": [
					{
						"verse": 16,
						"text": "And Jesus being baptized, forthwith came out of the water: and lo, the heavens were opened to him: and he saw the Spirit of God descending as a dove, and coming upon him."
					},
					{
						"verse": 17,
						"text": "And behold a voice from heaven saying: This is my beloved Son, in whom I am well pleased."
					}
				]
			}
		},
		{
			"title": "The second Luminous Mystery: The Wedding at Cana.",
			"reference": "Jn 2:1-5",
			"text": "«And the third day, there was a marriage in Cana of Galilee: and the mother of Jesus was there. And Jesus also was invited, and his disciples, to the marriage. And the wine failing, the mother of Jesus saith to him: They have no wine. And Jesus saith to her: Woman, what is that to me and to thee? My hour is not yet come. His mother saith to the waiters: Whatsoever he shall say to you, do ye.»",
			"verseData": {
				"book": "John",
				"chapter": 2,
				"verses": [
					{
						"verse": 1,
						"text": "And the third day, there was a marriage in Cana of Galilee: and the mother of Jesus was there."
					},
					{
						"verse": 2,
						"text": "And Jesus also was invited, and his disciples, to the marriage."
					},
					{
						"verse": 3,
						"text": "And the wine failing, the mother of Jesus saith to him: They have no wine."
					},
					{
						"verse": 4,
						"text": "And Jesus saith to her: Woman, what is that to me and to thee? My hour is not yet come."
					},
					{
						"verse": 5,
						"text": "His mother saith to the waiters: Whatsoever he shall say to you, do ye."
					}
				]
			}
		},
		{
			"title": "The third Luminous Mystery: The Proclamation of the Kingdom of God.",
			"reference": "Mk 1:15",
			"text": "«And saying: The time is accomplished and the kingdom of God is at hand. Repent and believe the gospel:»",
			"verseData": {
				"book": "Mark",
				"chapter": 1,
				"verses": [
					{
						"verse": 15,
						"text": "And saying: The time is accomplished and the kingdom of God is at hand. Repent and believe the gospel:"
					}
				]
			}
		},
		{
			"title": "The fourth Luminous Mystery: The Transfiguration.",
			"reference": "Mt 17:1-2",
			"text": "«And after six days Jesus taketh unto him Peter and James, and John his brother, and bringeth them up into a high mountain apart: And he was transfigured before them. And his face did shine as the sun: and his garments became white as snow.»",
			"verseData": {
				"book": "Matthew",
				"chapter": 17,
				"verses": [
					{
						"verse": 1,
						"text": "And after six days Jesus taketh unto him Peter and James, and John his brother, and bringeth them up into a high mountain apart:"
					},
					{
						"verse": 2,
						"text": "And he was transfigured before them. And his face did shine as the sun: and his garments became white as snow."
					}
				]
			}
		},
		{
			"title": "The fifth Luminous Mystery: The Institution of the Holy Eucharist.",
			"reference": "Mt 26:26",
			"text": "«And whilst they were at supper, Jesus took bread and blessed and broke and gave to his disciples and said: Take ye and eat. This is my body.»",
			"verseData": {
				"book": "Matthew",
				"chapter": 26,
				"verses": [
					{
						"verse": 26,
						"text": "And whilst they were at supper, Jesus took bread and blessed and broke and gave to his disciples and said: Take ye and eat. This is my body."
					}
				]
			}
		}
	],
	"freudenreich": [
		{
			"title": "The first Joyful Mystery: The Annunciation of the Archangel Gabriel to the Virgin Mary.",
			"reference": "Lk 1:26-27",
			"text": "«And in the sixth month, the angel Gabriel was sent from God into a city of Galilee, called Nazareth, To a virgin espoused to a man whose name was Joseph, of the house of David: and the virgin's name was Mary.»",
			"verseData": {
				"book": "Luke",
				"chapter": 1,
				"verses": [
					{
						"verse": 26,
						"text": "And in the sixth month, the angel Gabriel was sent from God into a city of Galilee, called Nazareth,"
					},
					{
						"verse": 27,
						"text": "To a virgin espoused to a man whose name was Joseph, of the house of David: and the virgin's name was Mary."
					}
				]
			}
		},
		{
			"title": "The second Joyful Mystery: The Visitation of Mary to Elizabeth.",
			"reference": "Lk 1:39-42",
			"text": "«And Mary rising up in those days, went into the hill country with haste into a city of Juda. And she entered into the house of Zachary and saluted Elizabeth. And it came to pass that when Elizabeth heard the salutation of Mary, the infant leaped in her womb. And Elizabeth was filled with the Holy Ghost. And she cried out with a loud voice and said: Blessed art thou among women and blessed is the fruit of thy womb.»",
			"verseData": {
				"book": "Luke",
				"chapter": 1,
				"verses": [
					{
						"verse": 39,
						"text": "And Mary rising up in those days, went into the hill country with haste into a city of Juda."
					},
					{
						"verse": 40,
						"text": "And she entered into the house of Zachary and saluted Elizabeth."
					},
					{
						"verse": 41,
						"text": "And it came to pass that when Elizabeth heard the salutation of Mary, the infant leaped in her womb. And Elizabeth was filled with the Holy Ghost."
					},
					{
						"verse": 42,
						"text": "And she cried out with a loud voice and said: Blessed art thou among women and blessed is the fruit of thy womb."
					}
				]
			}
		},
		{
			"title": "The third Joyful Mystery: The Nativity of Jesus in the Stable at Bethlehem.",
			"reference": "Lk 2:1-7",
			"text": "«And it came to pass that in those days there went out a decree from Caesar Augustus that the whole world should be enrolled. This enrolling was first made by Cyrinus, the governor of Syria. And all went to be enrolled, every one into his own city. And Joseph also went up from Galilee, out of the city of Nazareth, into Judea, to the city of David, which is called Bethlehem: because he was of the house and family of David. To be enrolled with Mary his espoused wife, who was with child. And it came to pass that when they were there, her days were accomplished that she should be delivered. And she brought forth her first born son and wrapped him up in swaddling clothes and laid him in a manger: because there was no room for them in the inn.»",
			"verseData": {
				"book": "Luke",
				"chapter": 2,
				"verses": [
					{
						"verse": 1,
						"text": "And it came to pass that in those days there went out a decree from Caesar Augustus that the whole world should be enrolled."
					},
					{
						"verse": 2,
						"text": "This enrolling was first made by Cyrinus, the governor of Syria."
					},
					{
						"verse": 3,
						"text": "And all went to be enrolled, every one into his own city."
					},
					{
						"verse": 4,
						"text": "And Joseph also went up from Galilee, out of the city of Nazareth, into Judea, to the city of David, which is called Bethlehem: because he was of the house and family of David."
					},
					{
						"verse": 5,
						"text": "To be enrolled with Mary his espoused wife, who was with child."
					},
					{
						"verse": 6,
						"text": "And it came to pass that when they were there, her days were accomplished that she should be delivered."
					},
					{
						"verse": 7,
						"text": "And she brought forth her first born son and wrapped him up in swaddling clothes and laid him in a manger: because there was no room for them in the inn."
					}
				]
			}
		},
		{
			"title": "The fourth Joyful Mystery: The Presentation of Jesus in the Temple.",
			"reference": "Lk 2:21-24",
			"text": "«And after eight days were accomplished, that the child should be circumcised, his name was called JESUS, which was called by the angel before he was conceived in the womb. And after the days of her purification, according to the law of Moses, were accomplished, they carried him to Jerusalem, to present him to the Lord: As it is written in the law of the Lord: Every male opening the womb shall be called holy to the Lord: And to offer a sacrifice, according as it is written in the law of the Lord, a pair of turtledoves or two young pigeons:»",
			"verseData": {
				"book": "Luke",
				"chapter": 2,
				"verses": [
					{
						"verse": 21,
						"text": "And after eight days were accomplished, that the child should be circumcised, his name was called JESUS, which was called by the angel before he was conceived in the womb."
					},
					{
						"verse": 22,
						"text": "And after the days of her purification, according to the law of Moses, were accomplished, they carried him to Jerusalem, to present him to the Lord:"
					},
					{
						"verse": 23,
						"text": "As it is written in the law of the Lord: Every male opening the womb shall be called holy to the Lord:"
					},
					{
						"verse": 24,
						"text": "And to offer a sacrifice, according as it is written in the law of the Lord, a pair of turtledoves or two young pigeons:"
					}
				]
			}
		},
		{
			"title": "The fifth Joyful Mystery: The Finding of Jesus in the Temple.",
			"reference": "Lk 2:41-47",
			"text": "«And his parents went every year to Jerusalem, at the solemn day of the pasch. And when he was twelve years old, they going up into Jerusalem, according to the custom of the feast, And having fulfilled the days, when they returned, the child Jesus remained in Jerusalem. And his parents knew it not. And thinking that he was in the company, they came a day's journey and sought him among their kinsfolks and acquaintance. And not finding him, they returned into Jerusalem, seeking him. And it came to pass, that, after three days, they found him in the temple, sitting in the midst of the doctors, hearing them and asking them questions. And all that heard him were astonished at his wisdom and his answers.»",
			"verseData": {
				"book": "Luke",
				"chapter": 2,
				"verses": [
					{
						"verse": 41,
						"text": "And his parents went every year to Jerusalem, at the solemn day of the pasch."
					},
					{
						"verse": 42,
						"text": "And when he was twelve years old, they going up into Jerusalem, according to the custom of the feast,"
					},
					{
						"verse": 43,
						"text": "And having fulfilled the days, when they returned, the child Jesus remained in Jerusalem. And his parents knew it not."
					},
					{
						"verse": 44,
						"text": "And thinking that he was in the company, they came a day's journey and sought him among their kinsfolks and acquaintance."
					},
					{
						"verse": 45,
						"text": "And not finding him, they returned into Jerusalem, seeking him."
					},
					{
						"verse": 46,
						"text": "And it came to pass, that, after three days, they found him in the temple, sitting in the midst of the doctors, hearing them and asking them questions."
					},
					{
						"verse": 47,
						"text": "And all that heard him were astonished at his wisdom and his answers."
					}
				]
			}
		}
	],
	"schmerzhaften": [
		{
			"title": "The first Sorrowful Mystery: The Agony of Jesus in the Garden.",
			"reference": "Mt 26:36-39",
			"text": "«Then Jesus came with them into a country place which is called Gethsemani. And he said to his disciples: Sit you here, till I go yonder and pray. And taking with him Peter and the two sons of Zebedee, he began to grow sorrowful and to be sad. Then he saith to them: My soul is sorrowful even unto death. Stay you here and watch with me. And going a little further, he fell upon his face, praying and saying: My Father, if it be possible, let this chalice pass from me. Nevertheless, not as I will but as thou wilt.»",
			"verseData": {
				"book": "Matthew",
				"chapter": 26,
				"verses": [
					{
						"verse": 36,
						"text": "Then Jesus came with them into a country place which is called Gethsemani. And he said to his disciples: Sit you here, till I go yonder and pray."
					},
					{
						"verse": 37,
						"text": "And taking with him Peter and the two sons of Zebedee, he began to grow sorrowful and to be sad."
					},
					{
						"verse": 38,
						"text": "Then he saith to them: My soul is sorrowful even unto death. Stay you here and watch with me."
					},
					{
						"verse": 39,
						"text": "And going a little further, he fell upon his face, praying and saying: My Father, if it be possible, let this chalice pass from me. Nevertheless, not as I will but as thou wilt."
					}
				]
			}
		},
		{
			"title": "The second Sorrowful Mystery: The Scourging at the Pillar.",
			"reference": "Mt 27:26",
			"text": "«Then he released to them Barabbas: and having scourged Jesus, delivered him unto them to be crucified.»",
			"verseData": {
				"book": "Matthew",
				"chapter": 27,
				"verses": [
					{
						"verse": 26,
						"text": "Then he released to them Barabbas: and having scourged Jesus, delivered him unto them to be crucified."
					}
				]
			}
		},
		{
			"title": "The third Sorrowful Mystery: The Crowning with Thorns.",
			"reference": "Mt 27:27-29",
			"text": "«Then the soldiers of the governor, taking Jesus into the hall, gathered together unto him the whole band. And stripping him, they put a scarlet cloak about him. And platting a crown of thorns, they put it upon his head, and a reed in his right hand. And bowing the knee before him, they mocked him, saying: Hail, King of the Jews.»",
			"verseData": {
				"book": "Matthew",
				"chapter": 27,
				"verses": [
					{
						"verse": 27,
						"text": "Then the soldiers of the governor, taking Jesus into the hall, gathered together unto him the whole band."
					},
					{
						"verse": 28,
						"text": "And stripping him, they put a scarlet cloak about him."
					},
					{
						"verse": 29,
						"text": "And platting a crown of thorns, they put it upon his head, and a reed in his right hand. And bowing the knee before him, they mocked him, saying: Hail, King of the Jews."
					}
				]
			}
		},
		{
			"title": "The fourth Sorrowful Mystery: Jesus Carries the Heavy Cross.",
			"reference": "Mk 15:21-22",
			"text": "«And they forced one Simon a Cyrenian, who passed by coming out of the country, the father of Alexander and of Rufus, to take up his cross. And they bring him into the place called Golgotha, which being interpreted is, The place of Calvary.»",
			"verseData": {
				"book": "Mark",
				"chapter": 15,
				"verses": [
					{
						"verse": 21,
						"text": "And they forced one Simon a Cyrenian, who passed by coming out of the country, the father of Alexander and of Rufus, to take up his cross."
					},
					{
						"verse": 22,
						"text": "And they bring him into the place called Golgotha, which being interpreted is, The place of Calvary."
					}
				]
			}
		},
		{
			"title": "The fifth Sorrowful Mystery: The Crucifixion of Jesus.",
			"reference": "Lk 23:33-46",
			"text": "«And when they were come to the place which is called Calvary, they crucified him there: and the robbers, one on the right hand, and the other on the left. And Jesus said: Father, forgive them, for they know not what they do. But they, dividing his garments, cast lots. And the people stood beholding. And the rulers with them derided him, saying: He saved others: let him save himself, if he be Christ, the elect of God. And the soldiers also mocked him, coming to him and offering him vinegar, And saying: If thou be the king of the Jews, save thyself. And there was also a superscription written over him in letters of Greek and Latin and Hebrew THIS IS THE KING OF THE JEWS. And one of those robbers who were hanged blasphemed him, saying: If thou be Christ, save thyself and us. But the other answering, rebuked him, saying: Neither dost thou fear God, seeing; thou art under the same condemnation? And we indeed justly: for we receive the due reward of our deeds. But this man hath done no evil. And he said to Jesus: Lord, remember me when thou shalt come into thy kingdom. And Jesus said to him: Amen I say to thee: This day thou shalt be with me in paradise. And it was almost the sixth hour: and there was darkness over all the earth until the ninth hour. And the sun was darkened, and the veil of the temple was rent in the midst. And Jesus crying with a loud voice, said: Father, into thy hands I commend my spirit. And saying this, he gave up the ghost.»",
			"verseData": {
				"book": "Luke",
				"chapter": 23,
				"verses": [
					{
						"verse": 33,
						"text": "And when they were come to the place which is called Calvary, they crucified him there: and the robbers, one on the right hand, and the other on the left."
					},
					{
						"verse": 34,
						"text": "And Jesus said: Father, forgive them, for they know not what they do. But they, dividing his garments, cast lots."
					},
					{
						"verse": 35,
						"text": "And the people stood beholding. And the rulers with them derided him, saying: He saved others: let him save himself, if he be Christ, the elect of God."
					},
					{
						"verse": 36,
						"text": "And the soldiers also mocked him, coming to him and offering him vinegar,"
					},
					{
						"verse": 37,
						"text": "And saying: If thou be the king of the Jews, save thyself."
					},
					{
						"verse": 38,
						"text": "And there was also a superscription written over him in letters of Greek and Latin and Hebrew THIS IS THE KING OF THE JEWS."
					},
					{
						"verse": 39,
						"text": "And one of those robbers who were hanged blasphemed him, saying: If thou be Christ, save thyself and us."
					},
					{
						"verse": 40,
						"text": "But the other answering, rebuked him, saying: Neither dost thou fear God, seeing; thou art under the same condemnation?"
					},
					{
						"verse": 41,
						"text": "And we indeed justly: for we receive the due reward of our deeds. But this man hath done no evil."
					},
					{
						"verse": 42,
						"text": "And he said to Jesus: Lord, remember me when thou shalt come into thy kingdom."
					},
					{
						"verse": 43,
						"text": "And Jesus said to him: Amen I say to thee: This day thou shalt be with me in paradise."
					},
					{
						"verse": 44,
						"text": "And it was almost the sixth hour: and there was darkness over all the earth until the ninth hour."
					},
					{
						"verse": 45,
						"text": "And the sun was darkened, and the veil of the temple was rent in the midst."
					},
					{
						"verse": 46,
						"text": "And Jesus crying with a loud voice, said: Father, into thy hands I commend my spirit. And saying this, he gave up the ghost."
					}
				]
			}
		}
	],
	"glorreichen": [
		{
			"title": "The first Glorious Mystery: The Resurrection of Jesus.",
			"reference": "Lk 24:1-6",
			"text": "«And on the first day of the week, very early in the morning, they came to the sepulchre, bringing the spices which they had prepared. And they found the stone rolled back from the sepulchre. And going in, they found not the body of the Lord Jesus. And it came to pass, as they were astonished in their mind at this, behold, two men stood by them, in shining apparel. And as they were afraid and bowed down their countenance towards the ground, they said unto them: Why seek you the living with the dead? He is not here, but is risen. Remember how he spoke unto you, when he was yet in Galilee,»",
			"verseData": {
				"book": "Luke",
				"chapter": 24,
				"verses": [
					{
						"verse": 1,
						"text": "And on the first day of the week, very early in the morning, they came to the sepulchre, bringing the spices which they had prepared."
					},
					{
						"verse": 2,
						"text": "And they found the stone rolled back from the sepulchre."
					},
					{
						"verse": 3,
						"text": "And going in, they found not the body of the Lord Jesus."
					},
					{
						"verse": 4,
						"text": "And it came to pass, as they were astonished in their mind at this, behold, two men stood by them, in shining apparel."
					},
					{
						"verse": 5,
						"text": "And as they were afraid and bowed down their countenance towards the ground, they said unto them: Why seek you the living with the dead?"
					},
					{
						"verse": 6,
						"text": "He is not here, but is risen. Remember how he spoke unto you, when he was yet in Galilee,"
					}
				]
			}
		},
		{
			"title": "The second Glorious Mystery: The Ascension of Jesus.",
			"reference": "Mk 16:19",
			"text": "«And the Lord Jesus, after he had spoken to them, was taken up into heaven and sitteth on the right hand of God.»",
			"verseData": {
				"book": "Mark",
				"chapter": 16,
				"verses": [
					{
						"verse": 19,
						"text": "And the Lord Jesus, after he had spoken to them, was taken up into heaven and sitteth on the right hand of God."
					}
				]
			}
		},
		{
			"title": "The third Glorious Mystery: The Descent of the Holy Spirit.",
			"reference": "Acts 2:1-4",
			"text": "«And when the days of the Pentecost were accomplished, they were all together in one place: And suddenly there came a sound from heaven, as of a mighty wind coming: and it filled the whole house where they were sitting. And there appeared to them parted tongues, as it were of fire: and it sat upon every one of them. And they were all filled with the Holy Ghost: and they began to speak with divers tongues, according as the Holy Ghost gave them to speak.»",
			"verseData": {
				"book": "Acts",
				"chapter": 2,
				"verses": [
					{
						"verse": 1,
						"text": "And when the days of the Pentecost were accomplished, they were all together in one place:"
					},
					{
						"verse": 2,
						"text": "And suddenly there came a sound from heaven, as of a mighty wind coming: and it filled the whole house where they were sitting."
					},
					{
						"verse": 3,
						"text": "And there appeared to them parted tongues, as it were of fire: and it sat upon every one of them."
					},
					{
						"verse": 4,
						"text": "And they were all filled with the Holy Ghost: and they began to speak with divers tongues, according as the Holy Ghost gave them to speak."
					}
				]
			}
		},
		{
			"title": "The fourth Glorious Mystery: The Assumption of Mary into Heaven.",
			"reference": "Lk 1:48-49",
			"text": "«Because he hath regarded the humility of his handmaid: for behold from henceforth all generations shall call me blessed. Because he that is mighty hath done great things to me: and holy is his name.»",
			"verseData": {
				"book": "Luke",
				"chapter": 1,
				"verses": [
					{
						"verse": 48,
						"text": "Because he hath regarded the humility of his handmaid: for behold from henceforth all generations shall call me blessed."
					},
					{
						"verse": 49,
						"text": "Because he that is mighty hath done great things to me: and holy is his name."
					}
				]
			}
		},
		{
			"title": "The fifth Glorious Mystery: The Coronation of Mary as Queen of Heaven and Earth.",
			"reference": "Apo 12:1",
			"text": "«And a great sign appeared in heaven: A woman clothed with the sun, and the moon under her feet, and on her head a crown of twelve stars.»",
			"verseData": {
				"book": "Apocalypse",
				"chapter": 12,
				"verses": [
					{
						"verse": 1,
						"text": "And a great sign appeared in heaven: A woman clothed with the sun, and the moon under her feet, and on her head a crown of twelve stars."
					}
				]
			}
		}
	]
};
