/** Generated by scripts/split-i18n.ts. */
/** DE calendar UI strings — source of truth for the key set. */

export const de = {
	today: "Heute",
	calendar: "Liturgischer Kalender",
	jumpToToday: "Zu heute",
	prev: "Vorheriger Monat",
	next: "Nächster Monat",
	psalterWeek: "Psalterwoche",
	cycle: "Lesejahr",
	rite1969Long: "Römisches Messbuch 1969 (Ordentliche Form)",
	rite1962Long: "Römisches Messbuch 1962 (Ausserordentliche Form)",
	wipTitle: "In Arbeit",
	wipBody: "Der Kalender für den alten Ritus (Messbuch 1962) ist noch nicht verfügbar. Bleib dran.",
	rite1962DisclaimerTitle: "Genauigkeit wird noch geprüft",
	rite1962DisclaimerBody: "Der Kalender für den Ritus von 1962 stammt aus divinum-officium-Daten und wird noch Tag für Tag mit maßgeblichen Quellen abgeglichen. Nur die in romcal enthaltenen Schweizer Diözesankalender werden angewendet; weitere Landes- oder Ortskalender sind noch nicht verfügbar.",
	calendarVariant: "Kalender",
	rite1969SwissNote: "romcal liefert für 1969 nur einen nationalen Schweizer Kalender — diözesane Unterkalender sind für diesen Ritus nicht verfügbar.",
} as const;
