/** Generated by scripts/split-i18n.ts. */
/** DE calendar (1962) UI strings — source of truth for the key set. */

export const de = {
	commemorations: "Kommemorationen",
	octave: "Oktav",
	octaveDay: "Tag",
	vigilOf: "Vigil von",
	transferredFrom: "Übertragen von",
	source: "Quelle",
	propers: "Messproprium",
	stationChurch: "Stationskirche",
	viewLatin: "Latein",
	viewParallel: "Parallel",
	viewVernacular: "Deutsch",
	fallbackBadge: "Allioli",
	fallbackHint: "Keine Übersetzung im Messbuch vorhanden. Text aus der Allioli-Bibelübersetzung an der angegebenen Stelle.",
} as const;
