/** Generated by scripts/split-i18n.ts. */
import type { de } from './de';

export const en = {
	today: "Today",
	calendar: "Liturgical Calendar",
	jumpToToday: "Jump to today",
	prev: "Previous month",
	next: "Next month",
	psalterWeek: "Psalter week",
	cycle: "Sunday cycle",
	rite1969Long: "Roman Missal of 1969 (Ordinary Form)",
	rite1962Long: "Roman Missal of 1962 (Extraordinary Form)",
	wipTitle: "Work in progress",
	wipBody: "The calendar for the older rite (1962 Missal) is not yet available. Stay tuned.",
	rite1962DisclaimerTitle: "Accuracy still being verified",
	rite1962DisclaimerBody: "The 1962 calendar is derived from divinum-officium data and is still being checked day-by-day against authoritative sources. Only the Swiss diocesan propers shipped by romcal are applied; other national/local calendars are not yet available.",
	calendarVariant: "Calendar",
	rite1969SwissNote: "romcal ships only a national Swiss calendar for 1969 — diocesan sub-calendars are not available for this rite.",
} as const satisfies Record<keyof typeof de, string>;
