/** Generated by scripts/split-i18n.ts. */
import type { de } from './de_1962';

export const en = {
	commemorations: "Commemorations",
	octave: "Octave",
	octaveDay: "day",
	vigilOf: "Vigil of",
	transferredFrom: "Transferred from",
	source: "Source",
	propers: "Mass propers",
	stationChurch: "Station church",
	viewLatin: "Latin",
	viewParallel: "Parallel",
	viewVernacular: "English",
	fallbackBadge: "Douay-Rheims",
	fallbackHint: "Translation not provided in the missal. Text taken from the Douay-Rheims Bible at the cited reference.",
} as const satisfies Record<keyof typeof de, string>;
