/** Generated by scripts/split-i18n.ts. */
import type { de } from './de';

export const la = {
	today: "Hodie",
	calendar: "Calendarium Liturgicum",
	jumpToToday: "Ad hodiernum",
	prev: "Mensis praecedens",
	next: "Mensis sequens",
	psalterWeek: "Hebdomada psalterii",
	cycle: "Cyclus dominicalis",
	rite1969Long: "Missale Romanum 1969 (Forma Ordinaria)",
	rite1962Long: "Missale Romanum 1962 (Forma Extraordinaria)",
	wipTitle: "In opere",
	wipBody: "Calendarium ritus antiqui (Missale 1962) nondum paratum est. Exspecta paulisper.",
	rite1962DisclaimerTitle: "Accuratio adhuc probanda",
	rite1962DisclaimerBody: "Calendarium anni 1962 ex datis divinum-officium ductum est et adhuc diebus singulis contra fontes fideles examinatur. Tantum calendaria propria dioecesium Helvetiae a romcal provisa adhibentur; cetera calendaria nationalia vel localia nondum praesto sunt.",
	calendarVariant: "Calendarium",
	rite1969SwissNote: "Pro anno 1969 romcal solum calendarium Helvetiae nationale praebet — calendaria dioecesana propria pro hoc ritu non adsunt.",
} as const satisfies Record<keyof typeof de, string>;
