/** Generated by scripts/split-i18n.ts. */
import type { de } from './de_1962';

export const la = {
	commemorations: "Commemorationes",
	octave: "Octava",
	octaveDay: "dies",
	vigilOf: "Vigilia",
	transferredFrom: "Translatum ex",
	source: "Fons",
	propers: "Propria Missæ",
	stationChurch: "Statio",
	viewLatin: "Latine",
	viewParallel: "Parallelum",
	viewVernacular: "Vernacula",
	fallbackBadge: "Vulgata",
	fallbackHint: "Interpretatio localis deest. Textus ex Biblia Sacra locis citatis.",
} as const satisfies Record<keyof typeof de, string>;
